### ISSUE TITLE
Nitpicky spacing

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/delay-repay#10]
Now that nitpicking is allowed, this spacing difference is annoying me
![image](https://github.com/georgejkaye/delay-repay/assets/69700997/8a0d15d5-c0f8-4e4b-8973-b76cc5c94565)
Observe how the top, bottom, and left spacing is larger than the right spacing.

**Comment by georgejkaye** [comment]
I've added some padding but the rendering of the date/time elements are platform specific (is that ios?) so I can't verify how it looks for you myself

**Comment by FrozenDude101** [comment]
Looks better on my end, Windows 10/Chrome 125

**Comment by FrozenDude101** [comment]
![image](https://github.com/georgejkaye/delay-repay/assets/69700997/efb01238-5cc2-4dcb-94c2-1d46bdd553dc)

**Comment by georgejkaye** [comment]
Good enough for me
