### ISSUE TITLE
Make button/non-button styling clearer

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/delay-repay#11]
![image](https://github.com/georgejkaye/delay-repay/assets/69700997/4afd07ff-1dd8-4cfb-8eec-1e3ec02c39c5)
Its sort of inconsistent as to what is a button and what is text.

All the input fields are uniformly white, and the buttons have a subtle hover effect, but the "remove ticket" button is styled completely differently, and the total cost and chosen ticket colours match the "add ticket" button despite not being button.

I think a non-colour way to determine what is and isn't a button would be useful

**Comment by georgejkaye** [comment]
Will think about this tonight
