### ISSUE TITLE
Add more TOCs

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/delay-repay#12]
Hoping this isn't showing my train amateurness, but I don't think any TfL services are listed?
[overground and elizabeth](https://tfl.gov.uk/fares/refunds-and-replacements/overground-and-elizabeth-line-delays)
[underground and dlr](https://tfl.gov.uk/fares/refunds-and-replacements/tube-and-dlr-delays)

It's kinda delay repay but not really, I think refunds because of a train being delayed still count even without the rhyme

Perhaps [eurostar](https://www.eurostar.com/uk-en/travel-info/service-information/claiming-compensation#Train-delayed) could also be added, its at least clearer about the requirements, but a bit more complicated.

**Comment by georgejkaye** [comment]
Turns out there's nuance for London Overground/Elizabeth Line (30-59 minutes gets you full refund only if it's TfL's fault, but 60+ gets you full refund regardless), so I'll need to add a section to make note of this.

**Comment by georgejkaye** [comment]
On a similar but different note, Eurostar offers different compensation depending on if you get an e-voucher or cash, so will need to list multiple different types of compensation. (Merseyrail does a thing like this too depending on if you travel wholly on Merseyrail services or not)

**Comment by georgejkaye** [comment]
I'll push the basic data now and work on the extra features later
