### ISSUE TITLE
Horizontal Overflow

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/delay-repay#18]
When on a mobile phone, the new delay repay table overflows and adds a horizontal scroll bar.
My phone isn't super big, so it won't affect everyone, but there's enough excess padding/margin around the table (especially the last column) to remove this.

**Comment by georgejkaye** [comment]
Can I have a screenshot please

**Comment by FrozenDude101** [comment]
no (jk one sec)

**Comment by FrozenDude101** [comment]
![Screenshot_2024-06-03-21-20-19-152_com.android.chrome.jpg](https://github.com/georgejkaye/delay-repay/assets/69700997/0a8802a3-f2c7-4b6f-8a00-b37875cc46ed)

![Screenshot_2024-06-03-21-20-16-294_com.android.chrome.jpg](https://github.com/georgejkaye/delay-repay/assets/69700997/ca3c52d5-81f8-4f5e-8ef3-d77953704ce9)

**Comment by FrozenDude101** [comment]
why are the pictures so big
anyway, top pic is all the way right, bottom is all the way left

**Comment by georgejkaye** [comment]
How does it look now

**Comment by FrozenDude101** [comment]
No overflow, but not a fan of the sgl / rtn

**Comment by georgejkaye** [comment]
No pleasing some people

**Comment by georgejkaye** [comment]
Will close for now
