### ISSUE TITLE
Significant delay when adding tickets

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/delay-repay#2]
pun intended

Steps to reproduce:
1. Add a ticket
2. Change the date/time, either expected or actual
3. Cannot add another ticket, or remove the added ticket

Sometimes it adds the ticket after a significant delay.

**Comment by georgejkaye** [comment]
Wonder why this is happening

**Comment by georgejkaye** [comment]
The tickets are stored in a map so maybe there's a key clash, but I don't know why that would happen

**Comment by FrozenDude101** [comment]
Why are the tickets stored in a map, it would make more sense to be an array

**Comment by georgejkaye** [comment]
So they can be updated in constant time

**Comment by FrozenDude101** [comment]
This is premature optimisation at its finest

**Comment by georgejkaye** [comment]
It's future proofing

**Comment by FrozenDude101** [comment]
Actually, its just incorrect logic, surely when the time chages *all* the tickets need to be updated?
So its linear anyway, as you need to go through them all, and iterating over an array is still linear

**Comment by georgejkaye** [comment]
The tickets just store a price and whether they're single/return, changing the time shouldn't affect them

**Comment by FrozenDude101** [comment]
I meant for updating the delay repay
Maps have marginal improvements here with adding/removing tickets, but lose out in generally representing the data how it is used
But this whole conversation is pointless anyway for your users (me) use case

**Comment by georgejkaye** [comment]
I use `Array.from` a lot anyway to convert it to an array so I might actually be making it worse performant

**Comment by georgejkaye** [comment]
![image](https://github.com/georgejkaye/delay-repay/assets/7274805/0edfc03a-663d-4a6d-b453-6391c731c97b)
I don't think it has anything to do with the map

**Comment by georgejkaye** [comment]
Fixed by 678ef5d, having the functions in the useEffect dependencies (which is what I thought the React warning was telling me to but maybe not) caused useEffect to call infinitely
