### ISSUE TITLE
Can't handle free tickets

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/delay-repay#3]
If a ticket costs £0, the delay repay is set to £0, regardless of other tickets
(This also happens for no cost tickets, maybe they're being interpreted as £0? (as they should))

Steps to reproduce:
1. Add a ticket with a non-zero cost.
2. Add a ticket with a cost of £0.
3. Set the delay repay
4. Observe that you get nothing

**Comment by georgejkaye** [comment]
I'm not getting this (although maybe that's because I've fixed the infinite useEffect issue)

**Comment by FrozenDude101** [comment]
maybe, I can't replicate it again now

**Comment by georgejkaye** [comment]
good enough for me
