### ISSUE TITLE
Cost input has the incorrect input type

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/delay-repay#4]
The cost boxes have the "text" input type, allowing anything to be input, including non-numbers.
"number" would be more appropriate, and can restrict the inputs to positive numbers, and additional +/- arrows set to 0.01 increments.

**Comment by georgejkaye** [comment]
Didn't even know you could do this, you learn something new every day

**Comment by FrozenDude101** [comment]
Can't believe I'm being forced to fix this

**Comment by georgejkaye** [comment]
Your input is appreciated as always
