### ISSUE TITLE
Clarify when there's no delay repay

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/delay-repay#9]
With the addition of different operators come different delay repay schemes
The 0-15 range is standard, but the 15-30 range is variable, and I think when in that delay range saying "0%" "0%" would make more sense (maybe with a <= X minutes where X is the first threshold?)

Also, the colour shouldn't change from green when it's still in the 0/0 repay range, such as for the sleeper between 15-30, which shows orangey brown

**Comment by georgejkaye** [comment]
A 'no compensation' badge now appears if there isn't a repay bracket, I'll think about how to do the colours later
